var hierarchy =
[
    [ "marvin::dsp::filters::Biquad< SampleType, NumStages >", "classmarvin_1_1dsp_1_1filters_1_1Biquad.html", null ],
    [ "marvin::dsp::filters::BiquadCoefficients< SampleType >", "structmarvin_1_1dsp_1_1filters_1_1BiquadCoefficients.html", null ],
    [ "marvin::containers::BufferView< SampleType >", "structmarvin_1_1containers_1_1BufferView.html", null ],
    [ "mostly_harmless::gui::Colour", "structmostly__harmless_1_1gui_1_1Colour.html", null ],
    [ "marvin::containers::StrideView< T, Stride >::const_iterator", "classmarvin_1_1containers_1_1StrideView_1_1const__iterator.html", null ],
    [ "marvin::dsp::DelayLine< SampleType, InterpolationType >", "classmarvin_1_1dsp_1_1DelayLine.html", null ],
    [ "marvin::dsp::spectral::FFT< SampleType >", "classmarvin_1_1dsp_1_1spectral_1_1FFT.html", null ],
    [ "marvin::containers::FixedCircularBuffer< T, N >", "classmarvin_1_1containers_1_1FixedCircularBuffer.html", null ],
    [ "marvin::dsp::spectral::getValueType< T >", "structmarvin_1_1dsp_1_1spectral_1_1getValueType.html", null ],
    [ "marvin::dsp::spectral::getValueType< T >", "structmarvin_1_1dsp_1_1spectral_1_1getValueType_3_01T_01_4.html", null ],
    [ "mostly_harmless::events::GuiToProcParamEvent", "structmostly__harmless_1_1events_1_1GuiToProcParamEvent.html", null ],
    [ "marvin::math::Hadamard< SampleType, size >", "classmarvin_1_1math_1_1Hadamard.html", null ],
    [ "marvin::math::Householder< SampleType, size >", "classmarvin_1_1math_1_1Householder.html", null ],
    [ "mostly_harmless::core::IEditor", "structmostly__harmless_1_1core_1_1IEditor.html", [
      [ "mostly_harmless::gui::WebviewBase", "classmostly__harmless_1_1gui_1_1WebviewBase.html", [
        [ "mostly_harmless::gui::WebviewEditor", "classmostly__harmless_1_1gui_1_1WebviewEditor.html", null ]
      ] ]
    ] ],
    [ "mostly_harmless::core::IEngine", "classmostly__harmless_1_1core_1_1IEngine.html", null ],
    [ "mostly_harmless::core::InitContext", "structmostly__harmless_1_1core_1_1InitContext.html", null ],
    [ "mostly_harmless::events::InputEventContext", "structmostly__harmless_1_1events_1_1InputEventContext.html", null ],
    [ "mostly_harmless::core::IPluginEntry", "structmostly__harmless_1_1core_1_1IPluginEntry.html", null ],
    [ "mostly_harmless::core::ISharedState", "classmostly__harmless_1_1core_1_1ISharedState.html", null ],
    [ "marvin::containers::StrideView< T, Stride >::iterator", "classmarvin_1_1containers_1_1StrideView_1_1iterator.html", null ],
    [ "marvin::dsp::filters::LatticeAPF< SampleType >", "classmarvin_1_1dsp_1_1filters_1_1LatticeAPF.html", null ],
    [ "marvin::math::LeakyIntegrator< SampleType >", "classmarvin_1_1math_1_1LeakyIntegrator.html", null ],
    [ "mostly_harmless::LoopInfo", "structmostly__harmless_1_1LoopInfo.html", null ],
    [ "marvin::dsp::filters::LPF< SampleType >", "classmarvin_1_1dsp_1_1filters_1_1LPF.html", null ],
    [ "marvin::dsp::oscillators::MultiOscillator< SampleType, Bandlimit >", "classmarvin_1_1dsp_1_1oscillators_1_1MultiOscillator.html", null ],
    [ "mostly_harmless::utils::NoDenormals", "classmostly__harmless_1_1utils_1_1NoDenormals.html", null ],
    [ "mostly_harmless::utils::OnScopeExit", "classmostly__harmless_1_1utils_1_1OnScopeExit.html", null ],
    [ "mostly_harmless::gui::WebviewBase::Options", "structmostly__harmless_1_1gui_1_1WebviewBase_1_1Options.html", null ],
    [ "marvin::dsp::oscillators::OscillatorBase< SampleType >", "classmarvin_1_1dsp_1_1oscillators_1_1OscillatorBase.html", [
      [ "marvin::dsp::oscillators::PulseOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1PulseOscillator.html", null ],
      [ "marvin::dsp::oscillators::SawOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1SawOscillator.html", null ],
      [ "marvin::dsp::oscillators::SquareOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1SquareOscillator.html", null ],
      [ "marvin::dsp::oscillators::TriOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1TriOscillator.html", null ],
      [ "marvin::dsp::oscillators::NoiseOscillator< SampleType >", "classmarvin_1_1dsp_1_1oscillators_1_1NoiseOscillator.html", null ],
      [ "marvin::dsp::oscillators::PulseOscillator< SampleType, Blep >", "classmarvin_1_1dsp_1_1oscillators_1_1PulseOscillator.html", null ],
      [ "marvin::dsp::oscillators::SawOscillator< SampleType, Blep >", "classmarvin_1_1dsp_1_1oscillators_1_1SawOscillator.html", null ],
      [ "marvin::dsp::oscillators::SineOscillator< SampleType >", "classmarvin_1_1dsp_1_1oscillators_1_1SineOscillator.html", null ],
      [ "marvin::dsp::oscillators::SquareOscillator< SampleType, Blep >", "classmarvin_1_1dsp_1_1oscillators_1_1SquareOscillator.html", null ],
      [ "marvin::dsp::oscillators::TriOscillator< SampleType, Blamp >", "classmarvin_1_1dsp_1_1oscillators_1_1TriOscillator.html", null ]
    ] ],
    [ "mostly_harmless::Parameter< SampleType >", "structmostly__harmless_1_1Parameter.html", null ],
    [ "mostly_harmless::ParameterID", "structmostly__harmless_1_1ParameterID.html", null ],
    [ "clap::helpers::Plugin", null, [
      [ "mostly_harmless::internal::PluginBase", "classmostly__harmless_1_1internal_1_1PluginBase.html", null ]
    ] ],
    [ "marvin::math::windows::PrecomputedWindow< SampleType, NumPoints >", "classmarvin_1_1math_1_1windows_1_1PrecomputedWindow.html", null ],
    [ "mostly_harmless::core::ProcessContext", "structmostly__harmless_1_1core_1_1ProcessContext.html", null ],
    [ "mostly_harmless::events::ProcToGuiParamEvent", "structmostly__harmless_1_1events_1_1ProcToGuiParamEvent.html", null ],
    [ "marvin::library::PropagateConst< T >", "classmarvin_1_1library_1_1PropagateConst.html", null ],
    [ "mostly_harmless::utils::Proxy< T >", "classmostly__harmless_1_1utils_1_1Proxy.html", null ],
    [ "marvin::utils::RandomGenerator< Engine >", "classmarvin_1_1utils_1_1RandomGenerator.html", null ],
    [ "marvin::utils::Range< T >", "structmarvin_1_1utils_1_1Range.html", null ],
    [ "marvin::math::Reciprocal< T >", "classmarvin_1_1math_1_1Reciprocal.html", null ],
    [ "marvin::math::ReciprocalRange< T >", "structmarvin_1_1math_1_1ReciprocalRange.html", null ],
    [ "mostly_harmless::gui::WebviewBase::Resource", "structmostly__harmless_1_1gui_1_1WebviewBase_1_1Resource.html", null ],
    [ "marvin::dsp::filters::SmoothedBiquadCoefficients< SampleType, InterpolationType, NumStages >", "classmarvin_1_1dsp_1_1filters_1_1SmoothedBiquadCoefficients.html", null ],
    [ "marvin::utils::SmoothedValue< SampleType, Type >", "classmarvin_1_1utils_1_1SmoothedValue.html", null ],
    [ "marvin::containers::fifos::SPSC< T >", "classmarvin_1_1containers_1_1fifos_1_1SPSC.html", null ],
    [ "marvin::containers::StrideView< T, Stride >", "classmarvin_1_1containers_1_1StrideView.html", null ],
    [ "marvin::dsp::filters::SVF< SampleType >", "classmarvin_1_1dsp_1_1filters_1_1SVF.html", null ],
    [ "marvin::dsp::filters::SVFResult< SampleType >", "structmarvin_1_1dsp_1_1filters_1_1SVFResult.html", null ],
    [ "marvin::containers::SwapBuffer< T >", "classmarvin_1_1containers_1_1SwapBuffer.html", null ],
    [ "mostly_harmless::utils::TaskThread", "classmostly__harmless_1_1utils_1_1TaskThread.html", null ],
    [ "mostly_harmless::utils::Timer", "classmostly__harmless_1_1utils_1_1Timer.html", null ],
    [ "mostly_harmless::TimeSignature", "structmostly__harmless_1_1TimeSignature.html", null ],
    [ "mostly_harmless::TransportState", "structmostly__harmless_1_1TransportState.html", null ],
    [ "mostly_harmless::events::WebEvent", "structmostly__harmless_1_1events_1_1WebEvent.html", null ],
    [ "marvin::math::interpolators::WindowedSincInterpolator< SampleType, N, WindowType >", "classmarvin_1_1math_1_1interpolators_1_1WindowedSincInterpolator.html", null ]
];